In [1]:
import tensorflow as tf

In [2]:
batch_size = 2
That = 3
N = 2

In [3]:
data = tf.random.uniform(shape=[batch_size, That, N])
print(data)

tf.Tensor(
[[[0.7375338  0.22997093]
  [0.5130764  0.20664358]
  [0.9655051  0.49819064]]

 [[0.85198474 0.91651165]
  [0.6761215  0.689976  ]
  [0.7915044  0.7800131 ]]], shape=(2, 3, 2), dtype=float32)


In [6]:
# previous mean & variance

old_mean = tf.math.reduce_mean(data)
old_var = tf.math.reduce_variance(data)

print('mean:', old_mean) # mean of every entries 
print('variance:', old_var) # variance of every entries

mean: tf.Tensor(0.6547527, shape=(), dtype=float32)
variance: tf.Tensor(0.056062642, shape=(), dtype=float32)


In [8]:
print('data:', data)
print('mean:', old_mean)
print('data-mean:', data-old_mean) # not `batch-wise` calculation

data: tf.Tensor(
[[[0.7375338  0.22997093]
  [0.5130764  0.20664358]
  [0.9655051  0.49819064]]

 [[0.85198474 0.91651165]
  [0.6761215  0.689976  ]
  [0.7915044  0.7800131 ]]], shape=(2, 3, 2), dtype=float32)
mean: tf.Tensor(0.6547527, shape=(), dtype=float32)
data-mean: tf.Tensor(
[[[ 0.08278114 -0.42478174]
  [-0.14167625 -0.4481091 ]
  [ 0.31075245 -0.15656203]]

 [[ 0.19723207  0.26175898]
  [ 0.0213688   0.03522331]
  [ 0.13675171  0.12526041]]], shape=(2, 3, 2), dtype=float32)


In [7]:
# proposed mean & variance

# use `axis` and `keepdims` options for `batch-wise` mean and var
new_mean = tf.math.reduce_mean(data, axis=[1, 2], keepdims=True)
new_var = tf.math.reduce_variance(data, axis=[1, 2], keepdims=True)

print('mean:', new_mean)
print('variance:', new_var)

mean: tf.Tensor(
[[[0.52515346]]

 [[0.7843518 ]]], shape=(2, 1, 1), dtype=float32)
variance: tf.Tensor(
[[[0.07141152]]

 [[0.00712184]]], shape=(2, 1, 1), dtype=float32)


In [9]:
print('data:', data)
print('mean:', new_mean)
print('data-mean:', data-new_mean) # `batch-wise` calculation

data: tf.Tensor(
[[[0.7375338  0.22997093]
  [0.5130764  0.20664358]
  [0.9655051  0.49819064]]

 [[0.85198474 0.91651165]
  [0.6761215  0.689976  ]
  [0.7915044  0.7800131 ]]], shape=(2, 3, 2), dtype=float32)
mean: tf.Tensor(
[[[0.52515346]]

 [[0.7843518 ]]], shape=(2, 1, 1), dtype=float32)
data-mean: tf.Tensor(
[[[ 0.21238035 -0.29518253]
  [-0.01207703 -0.31850988]
  [ 0.44035167 -0.02696282]]

 [[ 0.06763291  0.13215983]
  [-0.10823035 -0.09437585]
  [ 0.00715256 -0.00433874]]], shape=(2, 3, 2), dtype=float32)
